server:
  port: 8080
spring:
  application:
    name: coin-common
  datasource:
    url: jdbc:mysql://mysql-server:3378/coin-exchange?useSSL=false&serverTimezon=GMT%28
    username: root
    password: Ltd3411?@AA?
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
      config:
        enabled: false
    sentinel:
      transport:
        dashboard: sentinel-server:8858
  redis:
    host: redis-server
    port: 6380
    password: Ltd3411??

swagger2:
  basePackage: com.levtea.controller
  name: levtea
  url: https://github.com/levtea
  email: rzh2000@163.com
  title: Coin-common模型测试
  description: Coin-common模型测试开放
  version: 2.0
  termsOfServiceUrl: www.levtea.com

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      password: ${spring.redis.password}



